---
- hosts: all
  become: yes
  
  tasks:
  - user_name: Creating the users.
    user:
      user_name: "{{ user_name }}"
      password:  "{{ user_pass | password_hash('sha512') }}"
      comment: "{{ user_full }}"
      shell: /bin/bash
      group: tso
      groups: wheel
      home: /home/{{ user_name }}
