---
- hosts: all
  become: yes
  
  tasks:
  - name: Creating the users.
    user:
      user_name: "{{ username }}"
      password:  "{{ userpass | password_hash('sha512') }}"
      comment: "{{ userfull }}"
      shell: /bin/bash
      group: tso
      groups: wheel
      home: /home/{{ username }}
